```js
/**
 * We often encounter error-value objects,
 * like in axios().catch. These do not need to be thrown.

 * But when we do encounter a real Error,  we need to throw it.
 * And then, it can be useful to continue handling the
 * error in code before throwing it:
 *
 *   e.g. rendering the error to the DOM.
 *
 * But if the ERROR HANDLING code also throws and error,
 * it may hide the original error.
 *
 *   e.g. axios.catch(throwIfHandlerFails(handleFailure))
 *
 * This function will try to handle the error safely within try/catch,
 * if handling fails, it will throw the original error
 */
const errorHandlerCatch = errorHandler => (error) => {
  // If real Error, needs to be thrown...
  if (error instanceof Error) {
    // ...but first lets try and continue handling it...
    try {
      errorHandler(error)
    } catch (secondaryError) {
      // ... handling did not complete...
    }
    // ...throw the error.
    throw error
  } else {
    // Else is not a real Error, continue as normal.
    errorHandler(error)
  }
}

export default errorHandlerCatch
```

# Importing default


I don't know why, this is equivalent


```
16.4.5.2 The default export is just another named export 

The default export is actually just a named export with the special name default. That is, the following two statements are equivalent:

import { default as foo } from 'lib';
import foo from 'lib';
```
- http://exploringjs.com/es6/ch_modules.html#_the-default-export-is-just-another-named-export



```
import {default as thing} from "blah"
```

Can I also do 

```
import {default as thing, widget} from "blah"
```

https://hacks.mozilla.org/2015/08/es6-in-depth-modules/